In [55]:
import numpy as np

# 1. Create a 3x3x3 array with random values

In [56]:
random_array = np.random.rand(3, 3, 3)
random_array

array([[[0.34251955, 0.96992486, 0.66256252],
        [0.25809902, 0.78195706, 0.40309735],
        [0.23615002, 0.28859054, 0.15615824]],

       [[0.14558903, 0.77500798, 0.38901682],
        [0.25976864, 0.81710685, 0.17061567],
        [0.47858598, 0.1015154 , 0.37813942]],

       [[0.10686541, 0.81498856, 0.94574274],
        [0.42328824, 0.16288894, 0.82903041],
        [0.25710585, 0.63353764, 0.84059947]]])

# 2.Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [57]:
matrix = np.diag(1 + np.arange(4), k=-1)
matrix

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

# 3.Create a 8x8 matrix and fill it with a checkerboard pattern

In [58]:
checkerboard = np.zeros((8, 8), dtype=int)
checkerboard[1::2, ::2] = 1
checkerboard[::2, 1::2] = 1
checkerboard

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

# 4. Normalize a 5x5 random matrix

In [59]:
random_matrix = np.random.rand(5, 5)
normalized_matrix = (random_matrix - random_matrix.min()) / (random_matrix.max() - random_matrix.min())
normalized_matrix 

array([[0.88335122, 0.92155671, 0.54708635, 0.94423886, 0.79720666],
       [0.        , 0.62454279, 1.        , 0.23819623, 0.4812827 ],
       [0.93590286, 0.58983134, 0.4192672 , 0.0914556 , 0.52495309],
       [0.76745827, 0.41085932, 0.14340834, 0.72379961, 0.25595787],
       [0.56922937, 0.98007276, 0.49798847, 0.93407584, 0.20047132]])

# 5. How to find common values between two arrays?

In [60]:
array1 = np.array([1, 2, 3, 4, 5])
array2 = np.array([3, 4, 5, 6, 7])
common_values = np.intersect1d(array1, array2)
common_values

array([3, 4, 5])

# 6. How to get the dates of yesterday, today and tomorrow?

In [61]:
from datetime import datetime, timedelta
today = datetime.now()
yesterday = today - timedelta(days=1)
tomorrow = today + timedelta(days=1)
print("Yesterday:", yesterday.strftime("%Y-%m-%d"))
print("Today:", today.strftime("%Y-%m-%d"))
print("Tomorrow:", tomorrow.strftime("%Y-%m-%d"))


Yesterday: 2023-09-20
Today: 2023-09-21
Tomorrow: 2023-09-22


# 7. Consider two random array A and B, check if they are equal

In [62]:
array_A = np.random.rand(5)
array_B = np.random.rand(5)
are_equal = np.array_equal(array_A, array_B)
are_equal

False

# 8.Create random vector of size 10 and replace the maximum value by 0

In [63]:
random_vector = np.random.rand(10)
max_value_index = np.argmax(random_vector)
random_vector[max_value_index] = 0
random_vector

array([0.29847315, 0.39600855, 0.29909392, 0.57068144, 0.12320204,
       0.19367776, 0.04049408, 0.        , 0.01101325, 0.38766536])

# 9. How to print all the values of an array?

In [64]:
array = np.array([1, 2, 3, 4, 5])
print(array)

[1 2 3 4 5]


# 10.Subtract the mean of each row of a matrix

In [65]:
matrix = np.random.rand(3, 3)
row_means = np.mean(matrix, axis=1)
matrix_minus_means = matrix - row_means[:, np.newaxis]
matrix_minus_means

array([[-0.42279477,  0.30337289,  0.11942188],
       [ 0.15613869,  0.20592077, -0.36205946],
       [-0.20232678, -0.03907284,  0.24139961]])

# 11.Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)?

In [66]:
vector = np.random.rand(10)
indices_to_add_one = np.array([1, 3, 5, 3])  
vector[indices_to_add_one] += 1
vector 

array([0.16737182, 1.4342868 , 0.75651416, 1.2803272 , 0.46169293,
       1.07944801, 0.9838844 , 0.56113354, 0.61045301, 0.81685903])

# 12.How to get the diagonal of a dot product?

In [67]:
matrix1 = np.random.rand(3, 3)
matrix2 = np.random.rand(3, 3)
dot_product = np.dot(matrix1, matrix2)
diagonal = np.diag(dot_product)
diagonal

array([0.97657595, 0.43849374, 0.84472379])

# 13.How to find the most frequent value in an array?

In [68]:
x=np.random.randint(0,10,50)
most_frequent_value = np.bincount(x).argmax()
most_frequent_value 

2

# 14.How to get the n largest values of an array

In [69]:
a1 = np.array([1, 2, 3, 4])
a2 = np.array(['Red', 'Green', 'White', 'Orange'])
result = np.core.records.fromarrays([a1, a2], names='a,b')
print(result)


[(1, 'Red') (2, 'Green') (3, 'White') (4, 'Orange')]


# 15.How to create a record array from a regular array?

In [70]:
array = np.array([3, 1, 4, 1, 5, 9, 2, 6, 5, 3])
n_largest_values = np.partition(array, -3)[-3:] 
n_largest_values

array([5, 6, 9])

# 16. How to swap two rows of an array?

In [71]:
matrix = np.random.rand(3, 3)
matrix[[0, 2]] = matrix[[2, 0]]
matrix

array([[0.07078284, 0.53919591, 0.70648867],
       [0.67610542, 0.18543405, 0.21497379],
       [0.25536212, 0.3576307 , 0.58392365]])

# 17. Write python code to reshape to the next dimension of numpy array?

In [72]:
x = np.array([[24, 34, 121], [23, 22, 67], [686, 434, 123]])
reshaped_array = x.reshape(-1, 3)

print(reshaped_array)

[[ 24  34 121]
 [ 23  22  67]
 [686 434 123]]
